# Generated by Django 4.0 on 2023-09-14 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('image', models.ImageField(upload_to='Student/profile')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=225, unique=True)),
                ('password', models.CharField(default='', max_length=50)),
                ('DOB', models.DateField()),
                ('usertype', models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], default='student', max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='provider_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=10)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='accounts.user')),
            ],
        ),
    ]
