# Generated by Django 4.0 on 2023-09-14 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=10)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='accounts.user')),
            ],
        ),
        migrations.DeleteModel(
            name='provider_token',
        ),
    ]
