# Generated by Django 4.0 on 2023-09-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_token_delete_provider_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cls_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
